movieproject/movieapp/urls.py
from . import views
from django.urls import path

app_name='movieapp'

urlpatterns = [

    path('', views.movie, name='movie'),
    path('movie/<int:movie_id>/', views.detail, name='detail'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')
]

movieproject/movieproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movieapp.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models


# Create your models here.
class Movie(models.Model):
    name = models.CharField(max_length=250)
    disc = models.TextField()
    year = models.IntegerField()
    img = models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

movieproject/movieapp/forms.py
from django import forms
from .models import Movie


class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ['name', 'disc', 'year', 'img']

movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from .forms import MovieForm
from .models import Movie


# Create your views here.
def movie(request):
    movie = Movie.objects.all()
    context = {
        'movie_list': movie
    }
    return render(request, 'index.html', context)
def detail(request,movie_id):
    movie=Movie.objects.get(id=movie_id)
    return render(request,"detail.html",{'movie':movie})
   # return HttpResponse ("this is movie no %s " %movie_id)


def add_movie(request):
    if request.method=="POST":
        name=request.POST.get('name')
        disc = request.POST.get('disc')
        year = request.POST.get('year')
        img = request.FILES['img']
        movie=Movie(name=name,disc=disc,year=year,img=img)
        movie.save()
    return render(request,'add.html')

def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None,request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form, 'movie':movie})

def delete(request,id):
    if request.method=='POST':
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

movieproject/templates/add.html
{%extends 'base.html' %}
{%block body %}

<form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <input type="text", name="name" placeholder="Entermovie name">
      <input type="text", name="disc" placeholder="enter details">
      <input type="text", name="year" placeholder="Enteryear of release">
      <input type="file", name="img">
<input type="submit">
</form>
{% endblock %}

movieproject/templates/base.html
{%load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{%static 'style.css' %}">
</head>
<body>
<!-- As a link -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
      Movie library
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movieproject/templates/delete.html
<form method="POST">
  {% csrf_token%}
  Are you want to delete this movie?
  <input type="submit">
</form>

movieproject/templates/detail.html
{%extends 'base.html' %}
{%block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.img.url}}" width="300" height="300">

        </div>

<div class="col-md-6">
    <h3>{{movie.name}}</h3>
    <h4>{{movie.disc}}</h4>
    <h3>{{movie.year}}</h3>
    <a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">update</a>
    <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">delete</a>

</div>



    </div>
</div>
{% endblock %}

movieproject/templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

movieproject/templates/index.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <div class="row mx-auto">
        {% for i in movie_list %}
             <div class="col-12 col-sm-12 col-md-4  col-lg-4">
                <div class="card text-center col-12 col-sm-12 col-md-4  col-lg-4" style="max-width: 18rem;">
  <img class="card-img-top my_image" src="{{i.img.url}}" alt="Card image cap" style="min-height:20rem" style="min-width:10rem" style="background-color: #00AA9E; " >
                     <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.disc}}</p>
    <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">Go somewhere</a>
                    </div>
                </div>
             </div>
        {% endfor %}
    </div>
</div>






{% endblock %}